apiVersion: v1
kind: Namespace
metadata:
  name: bla-bla-bla
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: bla-bla-bla
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
